Adds example group-level analysis for phase-coherence effect
JoseAlanis/mne-stats pull request #11
Opened 2019-07-25 17:43 UTC by JoseAlanis

- Plot the group-level effect of predictor phase-coherence in LIMO dataset (results consistent with Fig. 4 B3 in [[1]](https://www.hindawi.com/journals/cin/2011/831409/)
- Add 95 % bootstrap CI.
- [WIP]: Bootstrap T-values results.

Rendered fig.:
![mean_beta_pc](https://user-images.githubusercontent.com/12409129/61895985-40a0d680-af14-11e9-9ce3-4110b427548d.png)

2019-07-25 17:44 UTC, JoseAlanis commented
sorry, don't pay attention to the commit message (forgot to update from other commit)

2019-07-25 20:59 UTC, dengemann commented
ping us when you need feedback.

> On 25 Jul 2019, at 19:44, José C. García Alanis <notifications@github.com> wrote:
> 
> sorry, don't pay attention to the commit message (forgot to update from other commit)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-07-25 21:02 UTC, jona-sassenhagen commented
Looks like a decent start.

2019-07-25 21:07 UTC, dengemann commented
I notice a double bootstrap here.
One is for the subjects ?
For now I would keep the ERPs fixed. We can later propagate the uncertainty from level 1 to 2. What do you think ?

2019-07-25 21:10 UTC, jona-sassenhagen commented
Simpler is better I guess. Reduce to the core added element and reduce overlap with other places.

2019-07-26 06:35 UTC, JoseAlanis commented
> I notice a double bootstrap here.
> One is for the subjects ?
> For now I would keep the ERPs fixed. We can later propagate the uncertainty from level 1 to 2. What do you think ?

double bootstrap? sorry I'm not sure what you mean. I'm taking random samples of subjects form the previosly computed betas-array; it contains the lm-results for each subject in th LIMO dataset. The average ERP is just the average of this results and the CI is computed with the random samples of subjects in line 144.

2019-07-26 06:39 UTC, dengemann commented
> The average ERP is just the average of this results and the CI is computed with the random samples of subjects in line 144.

You are right, I did not look carefully. You just looped over subjects. The heat in Paris ...

2019-07-26 13:35 UTC, JoseAlanis commented
Hey guys, I added the code for the group-level one-sample t-test and bootstrap-t.
I computed the upper and lower boundaries for the bootstrap t-test (see lines 234-265). However, I'm not entirely sure about the computation of the p-values for the bootstrap-t. Essentially they should be equivalent to "the average number of times the T-values obtained from original data are above or below the bootstrap quantiles" (see [[1]](https://www.hindawi.com/journals/cin/2011/831409/)) ... still struggling to get the idea behind this procedure.

Anyways. Here the rendered results from the one-sample t-test (unmasked as no p-values so far) the fig are consistent with Fig. 4 B1 and B2 in [[1]](https://www.hindawi.com/journals/cin/2011/831409/)

![1samp_tt](https://user-images.githubusercontent.com/12409129/61955299-fcb4dc80-afba-11e9-8723-1d533effc4b1.png)
![1samp_tt_topo](https://user-images.githubusercontent.com/12409129/61955307-fe7ea000-afba-11e9-8722-f306a74842a5.png)

2019-07-26 14:56 UTC, dengemann commented
@JoseAlanis can you show the T histograms along time? They are H1 and should thus be nice to look at, no?

2019-07-29 07:54 UTC, JoseAlanis commented
Hey, good idea, something like this?

.120 s
![thist_120](https://user-images.githubusercontent.com/12409129/62031085-d4112a80-b1e6-11e9-98bb-15b4a0b136ec.png)

.160 s
![thist_160](https://user-images.githubusercontent.com/12409129/62031101-de332900-b1e6-11e9-81c2-8e93f543825c.png)

2019-07-29 08:07 UTC, JoseAlanis commented
Hey I changed the bootstrap-t part a little bit, I misunderstood the approach the first time but should be consistent with the LIMO-paper now.
For completeness here are the rendered results of the group-level one-sample t-test (histograms are above).

![t-image](https://user-images.githubusercontent.com/12409129/62031859-96ad9c80-b1e8-11e9-8660-bc481e0b7459.png)
![t-map](https://user-images.githubusercontent.com/12409129/62031867-990ff680-b1e8-11e9-9e2b-fa4672436a66.png)

2019-07-29 08:17 UTC, dengemann commented
The histograms are not centered.
Any idea why that is?

> On 29 Jul 2019, at 10:07, José C. García Alanis <notifications@github.com> wrote:
> 
> Hey I changed the bootstrap-t part a little bit, I misunderstood the approach the first time but should be consistent with the LIMO-paper now.
> For completeness here are the rendered results of the group-level one-sample t-test (histograms are above).
> 
> 
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-07-30 10:48 UTC, JoseAlanis commented
The boot-t was not quite right. I adapted the code to be consistent with whats done in the LIMO-toolbox; i.e., centering the bootstrap samples around the population mean (i.e., mean of original betas) and dividing by the standard error of the bootstrap sample to obtain the sample T-values.

Here the updated results:

Robust CI (computed using boot-t quantiles) for the group-level effect of phase-coherence:
![beta_pc](https://user-images.githubusercontent.com/12409129/62123028-4d804a00-b2c7-11e9-913b-304ec3f64428.png)

Histogram of boot-t at around .120 s at electrode C1:
![boot_t_120ms](https://user-images.githubusercontent.com/12409129/62123107-7bfe2500-b2c7-11e9-8e9f-327922cc4d4b.png)

Group-level one-sample t-test for phase-coherence showing full electrode*time space with significance level derived using boot-t technique (significant values are above or below boot-t quantiles):
![1sampttest_masked](https://user-images.githubusercontent.com/12409129/62123264-dc8d6200-b2c7-11e9-8678-933f9f0b7ad2.png)

2019-08-18 20:32 UTC, jona-sassenhagen commented
What are we waiting for here?

2019-08-18 20:32 UTC, jona-sassenhagen requested changes

2019-08-18 20:32 UTC, jona-sassenhagen commented on examples/group_level/plot_group_level_effects.py
> +plt.title('electrode %s, time ~ .200 s' % electrode)
I'd really loop over times here instead. The code is already very long.

2019-08-20 09:30 UTC, JoseAlanis commented on examples/group_level/plot_group_level_effects.py
> +plt.title('electrode %s, time ~ .200 s' % electrode)
the idea was to show that the histograms are centered around zero. I think one time-period is enough to make this point. I'll just delete the other two.

2019-08-21 09:45 UTC, merged